# label data in [data] folders
# author: Zoe Lapomme

#method to return dictionary with json file name as key and reliability rating as value
def getReliability () :

    #create dictionary
    reliability = {}

    #add each file with corresponding reliability
    for s in ../../data :
        if s = "abc-news-au.json" :
            reliability [s] = 6
        elif s = "abc-news.json" :
            reliability [s] = 6
        elif s = "al-jazeera-english.json" :
            reliability [s] = 6
        elif s = "ars-technica.json" :
            reliability [s] = 6
        elif s = "associated-press.json" :
            reliability [s] = 9
        elif s = "australian-financial-review.json" :
            reliability [s] = 6
        elif s = "axios.json" :
            reliability [s] = 8
        elif s = "bbc-news.json" :
            reliability [s] = 9
        elif s = "bbc-sport.json" :
            reliability [s] = 8
        elif s = "bleacher-report.json" :
            reliability [s] = 4
        elif s = "bloomberg.json" :
            reliability [s] = 7
        elif s = "breitbart-news.json" :
            reliability [s] = 1
        elif s = "business-insider-uk.json" :
            reliability [s] = 5
        elif s = "business-insider.json" :
            reliability [s] = 6
        elif s = "buzzfeed.json" :
            reliability [s] = 3
        elif s = "cbc-news.json" :
            reliability [s] = 7
        elif s = "cbs-news.json" :
            reliability [s] = 7
        elif s = "cnbc.json" :
            reliability [s] = 7
        elif s = "cnn-es.json" :
            reliability [s] = 4
        elif s = "cnn.json" :
            reliability [s] = 5
        elif s = "crypto-coins-news.json" :
            reliability [s] = 2
        elif s = "daily-mail.json" :
            reliability [s] = 3
        elif s = "engadget.json" :
            reliability [s] = 5
        elif s = "entertainment-weekly.json" :
            reliability [s] = 3
        elif s = "espn-cric-info.json" :
            reliability [s] = 6
        elif s = "espn.json" :
            reliability [s] = 7
        elif s = "financial-post.json" :
            reliability [s] = 7
        elif s = "financial-times.json" :
            reliability [s] = 7
        elif s = "fortune.json" :
            reliability [s] = 5
        elif s = "four-four-two.json" :
            reliability [s] = 2
        elif s = "fox-news.json" :
            reliability [s] = 2
        elif s = "fox-sports.json" :
            reliability [s] = 4
        elif s = "google-news-au.json" :
            reliability [s] = 4
        elif s = "google-news-ca.json" :
            reliability [s] = 4
        elif s = "google-news-uk.json" :
            reliability [s] = 4
        elif s = "google-news.json" :
            reliability [s] = 4
        elif s = "hacker-news.json" :
            reliability [s] = 5
        elif s = "ign.json" :
            reliability [s] = 5
        elif s = "independent.json" :
            reliability [s] = 7
        elif s = "maschable.json" :
            reliability [s] = 3
        elif s = "medical-news-today.json" :
            reliability [s] = 7
        elif s = "metro.json" :
            reliability [s] = 4
        elif s = "mirror.json" :
            reliability [s] = 3
        elif s = "msnbc.json" :
            reliability [s] = 2
        elif s = "mtv-news-uk.json" :
            reliability [s] = 1
        elif s = "mtv-news.json" :
            reliability [s] = 2
        elif s = "national-geographic.json" :
            reliability [s] = 7
        elif s = "national-review.json" :
            reliability [s] = 3
        elif s = "nbc-news.json" :
            reliability [s] = 7
        elif s = "new-scientist.json" :
            reliability [s] = 4
        elif s = "new-york-magazine.json" :
            reliability [s] = 4
        elif s = "news-com-au.json" :
            reliability [s] = 2
        elif s = "newsweek.json" :
            reliability [s] = 7
        elif s = "next-big-future.json" :
            reliability [s] = 5
        elif s = "nfl-news.json" :
            reliability [s] = 5
        elif s = "nhl-news.json" :
            reliability [s] = 6
        elif s = "politico.json" :
            reliability [s] = 8
        elif s = "polygon.json" :
            reliability [s] = 3
        elif s = "recode.json" :
            reliability [s] = 5
        elif s = "reddit-r-all.json" :
            reliability [s] = 1
        elif s = "reuters.json" :
            reliability [s] = 9
        elif s = "talksport.json" :
            reliability [s] = 3
        elif s = "techcrunch.json" :
            reliability [s] = 6
        elif s = "techradar.json" :
            reliability [s] = 3
        elif s = "the-american-conservative.json" :
            reliability [s] = 0
        elif s = "the-economist.json" :
            reliability [s] = 9
        elif s = "the-globe-and-mail.json" :
            reliability [s] = 8
        elif s = "the-guardian-au.json" :
            reliability [s] = 8
        elif s = "the-guardian-uk.json" :
            reliability [s] = 8
        elif s = "the-hill.json" :
            reliability [s] = 8
        elif s = "the-huffington-post.json" :
            reliability [s] = 3
        elif s = "the-lad-bible.json" :
            reliability [s] = 1
        elif s = "the-new-york-times.json" :
            reliability [s] = 8
        elif s = "the-next-web.json" :
            reliability [s] = 4
        elif s = "the-sport-bible.json" :
            reliability [s] = 0
        elif s = "the-telegraph.json" :
            reliability [s] = 6
        elif s = "the-verge.json" :
            reliability [s] = 6
        elif s = "the-wall-street-journal.json" :
            reliability [s] = 8
        elif s = "the-washington-post.json" :
            reliability [s] = 8
        elif s = "the-washington-times.json" :
            reliability [s] = 3
        elif s = "time.json" :
            reliability [s] = 8
        elif s = "usa-today.json" :
            reliability [s] = 7
        elif s = "vice-news.json" :
            reliability [s] = 5
        elif s = "wired.json" :
            reliability [s] = 4

    return reliability

def main () :
