# label data in [data] folders


reliability = {}
for s in ../../data :
    if s = "abc-news-au.json" :
        reliability [s] = 4
    elif s = "abc-news.json" :
        reliability [s] = 4
    elif s = "al-jazeera-english.json" :
        reliability [s] =
    elif s = "ars-technica.json" :
        reliability [s] =
    elif s = "associated-press.json" :
        reliability [s] =
    elif s = "australian-financial-review.json" :
        reliability [s] =
    elif s = "axios.json" :
        reliability [s] =
    elif s = "bbc-news.json" :
        reliability [s] =
    elif s = "bbc-sport.json" :
        reliability [s] =
    elif s = "bleacher-report.json" :
        reliability [s] =
    elif s = "bloomberg.json" :
        reliability [s] =
    elif s = "breitbart-news.json" :
        reliability [s] =
    elif s = "business-insider-uk.json" :
        reliability [s] =
    elif s = "business-insider.json" :
        reliability [s] =
    elif s = "buzzfeed.json" :
        reliability [s] =
    elif s = "cbc-news.json" :
        reliability [s] =
    elif s = "cbs-news.json" :
        reliability [s] =
    elif s = "cnbc.json" :
        reliability [s] =
    elif s = "cnn-es.json" :
        reliability [s] =
    elif s = "cnn.json" :
        reliability [s] =
    elif s = "crypto-coins-news.json" :
        reliability [s] =
    elif s = "daily-mail.json" :
        reliability [s] =
    elif s = "engadget.json" :
        reliability [s] =
    elif s = "entertainment-weekly.json" :
        reliability [s] =
    elif s = "espn-cric-info.json" :
        reliability [s] =
    elif s = "espn.json" :
        reliability [s] =
    elif s = "financial-post.json" :
        reliability [s] =
    elif s = "financial-times.json" :
        reliability [s] =
    elif s = "fortune.json" :
        reliability [s] =
    elif s = "four-four-two.json" :
        reliability [s] =
    elif s = "fox-news.json" :
        reliability [s] =
    elif s = "fox-sports.json" :
        reliability [s] =
    elif s = "google-news-au.json" :
        reliability [s] =
    elif s = "google-news-ca.json" :
        reliability [s] =
    elif s = "google-news-uk.json" :
        reliability [s] =
    elif s = "google-news.json" :
        reliability [s] =
    elif s = "hacker-news.json" :
        reliability [s] =
    elif s = "ign.json" :
        reliability [s] =
    elif s = "independent.json" :
        reliability [s] =
    elif s = "maschable.json" :
        reliability [s] =
    elif s = "medical-news-today.json" :
        reliability [s] =
    elif s = "metro.json" :
        reliability [s] =
    elif s = "mirror.json" :
        reliability [s] =
    elif s = "msnbc.json" :
        reliability [s] =
    elif s = "mtv-news-uk.json" :
        reliability [s] =
    elif s = "mtv-news.json" :
        reliability [s] =
    elif s = "national-geographic.json" :
        reliability [s] =
    elif s = "national-review.json" :
        reliability [s] =
    elif s = "nbc-news.json" :
        reliability [s] =
    elif s = "new-scientist.json" :
        reliability [s] =
    elif s = "new-york-magazine.json" :
        reliability [s] =
    elif s = "news-com-au.json" :
        reliability [s] =
    elif s = "newsweek.json" :
        reliability [s] =
    elif s = "next-big-future.json" :
        reliability [s] =
    elif s = "nfl-news.json" :
        reliability [s] =
    elif s = "nhl-news.json" :
        reliability [s] =
    elif s = "politico.json" :
        reliability [s] =
    elif s = "polygon.json" :
        reliability [s] =
    elif s = "recode.json" :
        reliability [s] =
    elif s = "reddit-r-all.json" :
        reliability [s] =
    elif s = "reuters.json" :
        reliability [s] =
    elif s = "talksport.json" :
        reliability [s] =
    elif s = 
